import type { IUser } from "./index";

const mockUsers: IUser[] = [
  {
    id: "1",
    name: "Professor X",
    teams: "X-Men, Illuminati",
    powers: "Telepathy, mind control, astral projection",
    firstAppearance: "1963",
  },
  {
    id: "2",
    name: "Cyclops",
    teams: "X-Men",
    powers: "Optic energy blasts",
    firstAppearance: "1963",
  },
  {
    id: "3",
    name: "Jean Grey",
    teams: "X-Men, Phoenix Force",
    powers: "Telepathy, telekinesis, cosmic energy manipulation",
    firstAppearance: "1963",
  },
  {
    id: "4",
    name: "Wolverine",
    teams: "X-Men, Avengers, Alpha Flight",
    powers: "Regeneration, enhanced senses, adamantium claws",
    firstAppearance: "1974",
  },
  {
    id: "5",
    name: "Storm",
    teams: "X-Men",
    powers: "Weather manipulation, flight",
    firstAppearance: "1975",
  },
  {
    id: "6",
    name: "Beast",
    teams: "X-Men, Avengers",
    powers: "Superhuman strength, agility, intellect",
    firstAppearance: "1963",
  },
  {
    id: "7",
    name: "Rogue",
    teams: "X-Men",
    powers: "Power absorption through touch",
    firstAppearance: "1981",
  },
  {
    id: "8",
    name: "Gambit",
    teams: "X-Men",
    powers: "Kinetic energy charging, agility",
    firstAppearance: "1990",
  },
  {
    id: "9",
    name: "Nightcrawler",
    teams: "X-Men",
    powers: "Teleportation, agility",
    firstAppearance: "1975",
  },
  {
    id: "10",
    name: "Colossus",
    teams: "X-Men",
    powers: "Organic steel transformation, super strength",
    firstAppearance: "1975",
  },
  {
    id: "11",
    name: "Magneto",
    teams: "Brotherhood of Mutants, X-Men",
    powers: "Magnetism manipulation",
    firstAppearance: "1963",
  },
  {
    id: "12",
    name: "Mystique",
    teams: "Brotherhood of Mutants",
    powers: "Shapeshifting",
    firstAppearance: "1978",
  },
  {
    id: "13",
    name: "Iceman",
    teams: "X-Men",
    powers: "Cryokinesis, ice form",
    firstAppearance: "1963",
  },
  {
    id: "14",
    name: "Kitty Pryde",
    teams: "X-Men",
    powers: "Intangibility, phasing",
    firstAppearance: "1980",
  },
  {
    id: "15",
    name: "Bishop",
    teams: "X-Men",
    powers: "Energy absorption and redirection",
    firstAppearance: "1991",
  },
];

export default mockUsers;
